### Java sdk configuration
network.peers[0]=127.0.0.1:null
### Optional. Default will search conf,config,src/main/conf/src/main/config
cryptoMaterial.certPath=conf

### System configuration
system.groupId=group0
system.hexPrivateKey=312ff60e3cd885bc896352884f3e316239020338bdd3de18708ef732b83afb12,a1c08fcd57940a0002205e8af9554b5f1a263a04609b2aa7ae6f0fe4528c34c3,9f5283996a6414298b19a0de9b7d4d507fd97ca7b06efb946b51100154ffd46d

### Contract configuration
contract.greenCertAddress=0x37a44585bf1e9618fdb4c62c4c96189a07dd4b48

### Springboot configuration
server.port=8080
server.session.timeout=60
banner.charset=UTF-8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

