spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# ??????? MySQL ??????????
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/blockchain_greencert?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=1110727

# JPA/Hibernate ?? (?????????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

### Java sdk configuration
network.peers[0]=192.168.85.128:20200
### Optional. Default will search conf,config,src/main/conf/src/main/config
cryptoMaterial.certPath=conf
cryptoMaterial.useSMCrypto=false
### System configuration
system.groupId=group0
system.hexPrivateKey=312ff60e3cd885bc896352884f3e316239020338bdd3de18708ef732b83afb12,a1c08fcd57940a0002205e8af9554b5f1a263a04609b2aa7ae6f0fe4528c34c3,9f5283996a6414298b19a0de9b7d4d507fd97ca7b06efb946b51100154ffd46d

### Contract configuration
contract.greenCertAddress=0x37a44585bf1e9618fdb4c62c4c96189a07dd4b48

### Springboot configuration
server.port=8080
server.session.timeout=60
banner.charset=UTF-8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

